name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  TZ: Asia/Jakarta
  IMAGE_NAME: gcloud-sdk-node
  HUB_IMAGE_NAME: cakhanif/gcloud-sdk-node
jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi
  
  push_docker_hub:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
        - uses: actions/checkout@v2
  
        - name: Build Image
          run: docker build . --file Dockerfile --tag $HUB_IMAGE_NAME
        
        - name: Login to Docker Registry
          run: |
            #Logout from previous stage
            docker logout
            
            #and login again
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u cakhanif --password-stdin

        - name: Push to Docker Registry
          shell: bash
          run: |           
            echo $HUB_IMAGE_NAME:
            
            echo $HUB_IMAGE_NAME:$(date '+%y%m%d%H%M')
            echo $(date '+%y%m%d%H%M')

            docker tag $HUB_IMAGE_NAME $HUB_IMAGE_NAME:$DATE
            
            #push to docker registry
            docker push $HUB_IMAGE_NAME:$DATE
            docker push $HUB_IMAGE_NAME
